# Generated by Django 2.2.7 on 2020-01-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.FileField(upload_to='profile_picture/'),
        ),
    ]
